# Generated by Django 4.2.5 on 2023-10-04 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('cod_gpr', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desc_gpr', models.TextField()),
                ('situ_gpr', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('cod_sbg', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desc_sbg', models.TextField()),
                ('situ_sgb', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('group_f', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('cod_psv', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('desc_psv', models.TextField()),
                ('situ_psv', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('group_f', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.group')),
                ('sub_group_f', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.subgroup')),
            ],
        ),
    ]
